language: node_js
sudo: required
dist: trusty
node_js: stable
cache:
  directories:
  - bower_components
  - node_modules
branches:
  only:
    - stage
    - develop
after_success:
  - node tasks/ci.js
